# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1198, 862)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setStyleSheet("background-color: rgb(23, 124, 193);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header_frame.setObjectName("header_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.header_frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_header = QtWidgets.QLabel(self.header_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setStyleSheet(
            "color: rgb(245, 247, 250);\n" "font-weight: bold;\n" ""
        )
        self.label_header.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_header.setObjectName("label_header")
        self.gridLayout_6.addWidget(self.label_header, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.header_frame, 0, 0, 1, 1)
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setStyleSheet("background-color: #12232E;\n" "color: white;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.main_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.output_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_frame.sizePolicy().hasHeightForWidth())
        self.output_frame.setSizePolicy(sizePolicy)
        self.output_frame.setMinimumSize(QtCore.QSize(640, 0))
        self.output_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.output_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.output_frame.setObjectName("output_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.output_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_image = QtWidgets.QLabel(self.output_frame)
        self.input_image.setText("")
        self.input_image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_image.setObjectName("input_image")
        self.gridLayout_2.addWidget(self.input_image, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.output_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint
        )
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_3.addItem(spacerItem)
        self.before_button = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.before_button.setFont(font)
        self.before_button.setCheckable(True)
        self.before_button.setChecked(True)
        self.before_button.setObjectName("before_button")
        self.horizontalLayout_3.addWidget(self.before_button)
        self.after_button = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.after_button.setFont(font)
        self.after_button.setCheckable(True)
        self.after_button.setObjectName("after_button")
        self.horizontalLayout_3.addWidget(self.after_button)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_2.addWidget(
            self.frame, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.verticalLayout_5.addWidget(self.output_frame)
        self.verticalLayout_5.setStretch(0, 4)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.form_frame = QtWidgets.QFrame(self.main_frame)
        self.form_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.form_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.form_frame.setObjectName("form_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.form_frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.gridLayout_3.addItem(spacerItem2, 10, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_detection = QtWidgets.QLabel(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_detection.setFont(font)
        self.label_detection.setObjectName("label_detection")
        self.verticalLayout_3.addWidget(self.label_detection)
        self.input_detection_type = QtWidgets.QComboBox(self.form_frame)
        self.input_detection_type.setObjectName("input_detection_type")
        self.verticalLayout_3.addWidget(self.input_detection_type)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.model_label = QtWidgets.QLabel(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.model_label.setFont(font)
        self.model_label.setObjectName("model_label")
        self.verticalLayout_2.addWidget(self.model_label)
        self.input_detection_model = QtWidgets.QComboBox(self.form_frame)
        self.input_detection_model.setObjectName("input_detection_model")
        self.verticalLayout_2.addWidget(self.input_detection_model)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.detect_button = QtWidgets.QPushButton(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.detect_button.setFont(font)
        self.detect_button.setStyleSheet("background-color: #177CC1;")
        self.detect_button.setObjectName("detect_button")
        self.horizontalLayout.addWidget(self.detect_button)
        self.pause_button = QtWidgets.QPushButton(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pause_button.setFont(font)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout.addWidget(self.pause_button)
        self.resume_button = QtWidgets.QPushButton(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.resume_button.setFont(font)
        self.resume_button.setStyleSheet("background-color: rgb(0, 173, 0)")
        self.resume_button.setObjectName("resume_button")
        self.horizontalLayout.addWidget(self.resume_button)
        self.stop_button = QtWidgets.QPushButton(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stop_button.setFont(font)
        self.stop_button.setStyleSheet("background-color: rgb(255, 20, 71);")
        self.stop_button.setDefault(False)
        self.stop_button.setFlat(False)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.save_button = QtWidgets.QPushButton(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.save_button.setFont(font)
        self.save_button.setStyleSheet("background-color: rgb(38,66,86);")
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancel_button.setFont(font)
        self.cancel_button.setStyleSheet("background-color: rgb(255, 20, 71);")
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.gridLayout_3.addLayout(self.horizontalLayout, 9, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_mode = QtWidgets.QLabel(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_mode.setFont(font)
        self.label_mode.setObjectName("label_mode")
        self.verticalLayout.addWidget(self.label_mode)
        self.input_mode = QtWidgets.QComboBox(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_mode.setFont(font)
        self.input_mode.setObjectName("input_mode")
        self.input_mode.addItem("")
        self.input_mode.addItem("")
        self.input_mode.addItem("")
        self.verticalLayout.addWidget(self.input_mode)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.import_layout = QtWidgets.QVBoxLayout()
        self.import_layout.setSpacing(5)
        self.import_layout.setObjectName("import_layout")
        self.label_import = QtWidgets.QLabel(self.form_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_import.setFont(font)
        self.label_import.setObjectName("label_import")
        self.import_layout.addWidget(self.label_import)
        self.input_import = QtWidgets.QLineEdit(self.form_frame)
        self.input_import.setStyleSheet("background-color: #1F3647;")
        self.input_import.setReadOnly(False)
        self.input_import.setPlaceholderText("")
        self.input_import.setClearButtonEnabled(True)
        self.input_import.setObjectName("input_import")
        self.import_layout.addWidget(self.input_import)
        self.gridLayout_3.addLayout(self.import_layout, 1, 0, 1, 1)
        self.checkbox_frame = QtWidgets.QFrame(self.form_frame)
        self.checkbox_frame.setAutoFillBackground(False)
        self.checkbox_frame.setStyleSheet("background-color: #1F3647;")
        self.checkbox_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.checkbox_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.checkbox_frame.setMidLineWidth(1)
        self.checkbox_frame.setObjectName("checkbox_frame")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.checkbox_frame)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.occ_class_5 = QtWidgets.QLabel(self.checkbox_frame)
        self.occ_class_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.occ_class_5.setObjectName("occ_class_5")
        self.gridLayout_7.addWidget(self.occ_class_5, 6, 1, 1, 1)
        self.class_5 = QtWidgets.QCheckBox(self.checkbox_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.class_5.setFont(font)
        self.class_5.setStyleSheet(
            "::indicator {\n"
            "    border: 1px solid grey;\n"
            "    background-color: #fff;\n"
            "}\n"
            "\n"
            "::indicator:checked {\n"
            '    image: url("assets/checked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}\n"
            "::indicator:unchecked {\n"
            '    image: url("assets/unchecked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}"
        )
        self.class_5.setChecked(True)
        self.class_5.setObjectName("class_5")
        self.gridLayout_7.addWidget(self.class_5, 6, 0, 1, 1)
        self.occ_class_3 = QtWidgets.QLabel(self.checkbox_frame)
        self.occ_class_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.occ_class_3.setObjectName("occ_class_3")
        self.gridLayout_7.addWidget(self.occ_class_3, 4, 1, 1, 1)
        self.class_4 = QtWidgets.QCheckBox(self.checkbox_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.class_4.setFont(font)
        self.class_4.setStyleSheet(
            "::indicator {\n"
            "    border: 1px solid grey;\n"
            "    background-color: #fff;\n"
            "}\n"
            "\n"
            "::indicator:checked {\n"
            '    image: url("assets/checked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}\n"
            "::indicator:unchecked {\n"
            '    image: url("assets/unchecked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}"
        )
        self.class_4.setChecked(True)
        self.class_4.setObjectName("class_4")
        self.gridLayout_7.addWidget(self.class_4, 5, 0, 1, 1)
        self.class_3 = QtWidgets.QCheckBox(self.checkbox_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.class_3.setFont(font)
        self.class_3.setStyleSheet(
            "::indicator {\n"
            "    border: 1px solid grey;\n"
            "    background-color: #fff;\n"
            "}\n"
            "\n"
            "::indicator:checked {\n"
            '    image: url("assets/checked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}\n"
            "::indicator:unchecked {\n"
            '    image: url("assets/unchecked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}"
        )
        self.class_3.setChecked(True)
        self.class_3.setObjectName("class_3")
        self.gridLayout_7.addWidget(self.class_3, 4, 0, 1, 1)
        self.class_2 = QtWidgets.QCheckBox(self.checkbox_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.class_2.setFont(font)
        self.class_2.setStyleSheet(
            "::indicator {\n"
            "    border: 1px solid grey;\n"
            "    background-color: #fff;\n"
            "}\n"
            "\n"
            "::indicator:checked {\n"
            '    image: url("assets/checked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}\n"
            "::indicator:unchecked {\n"
            '    image: url("assets/unchecked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}"
        )
        self.class_2.setChecked(True)
        self.class_2.setObjectName("class_2")
        self.gridLayout_7.addWidget(self.class_2, 3, 0, 1, 1)
        self.occ_class_1 = QtWidgets.QLabel(self.checkbox_frame)
        self.occ_class_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.occ_class_1.setObjectName("occ_class_1")
        self.gridLayout_7.addWidget(self.occ_class_1, 2, 1, 1, 1)
        self.class_0 = QtWidgets.QCheckBox(self.checkbox_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.class_0.setFont(font)
        self.class_0.setStyleSheet(
            "::indicator {\n"
            "    border: 1px solid grey;\n"
            "    background-color: #fff;\n"
            "}\n"
            "\n"
            "::indicator:checked {\n"
            '    image: url("assets/checked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}\n"
            "::indicator:unchecked {\n"
            '    image: url("assets/unchecked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}"
        )
        self.class_0.setChecked(True)
        self.class_0.setObjectName("class_0")
        self.gridLayout_7.addWidget(self.class_0, 0, 0, 1, 1)
        self.occ_class_4 = QtWidgets.QLabel(self.checkbox_frame)
        self.occ_class_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.occ_class_4.setObjectName("occ_class_4")
        self.gridLayout_7.addWidget(self.occ_class_4, 5, 1, 1, 1)
        self.class_1 = QtWidgets.QCheckBox(self.checkbox_frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.class_1.setFont(font)
        self.class_1.setStyleSheet(
            "::indicator {\n"
            "    border: 1px solid grey;\n"
            "    background-color: #fff;\n"
            "}\n"
            "\n"
            "::indicator:checked {\n"
            '    image: url("assets/checked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}\n"
            "::indicator:unchecked {\n"
            '    image: url("assets/unchecked.png");\n'
            "    height: 1em;\n"
            "    width: 1em;\n"
            "}"
        )
        self.class_1.setChecked(True)
        self.class_1.setObjectName("class_1")
        self.gridLayout_7.addWidget(self.class_1, 2, 0, 1, 1)
        self.occ_class_0 = QtWidgets.QLabel(self.checkbox_frame)
        self.occ_class_0.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.occ_class_0.setObjectName("occ_class_0")
        self.gridLayout_7.addWidget(self.occ_class_0, 0, 1, 1, 1)
        self.occ_class_2 = QtWidgets.QLabel(self.checkbox_frame)
        self.occ_class_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.occ_class_2.setObjectName("occ_class_2")
        self.gridLayout_7.addWidget(self.occ_class_2, 3, 1, 1, 1)
        self.gridLayout_3.addWidget(self.checkbox_frame, 8, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.form_frame)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 7)
        self.gridLayout_4.setColumnStretch(1, 3)
        self.gridLayout.addWidget(self.main_frame, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1198, 20))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuMain.addAction(self.actionExit)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_header.setText(
            _translate("MainWindow", "DISTRIBUTION LINE DETECTION")
        )
        self.before_button.setText(_translate("MainWindow", "Before"))
        self.after_button.setText(_translate("MainWindow", "After"))
        self.label_2.setText(_translate("MainWindow", "Components"))
        self.label_3.setText(_translate("MainWindow", "Occurence"))
        self.label_detection.setText(_translate("MainWindow", "Detection Type"))
        self.model_label.setText(_translate("MainWindow", "Detection Model"))
        self.detect_button.setText(_translate("MainWindow", "Detect"))
        self.pause_button.setText(_translate("MainWindow", "Pause"))
        self.resume_button.setText(_translate("MainWindow", "Resume"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.cancel_button.setText(_translate("MainWindow", "Cancel"))
        self.label_mode.setText(_translate("MainWindow", "Mode"))
        self.input_mode.setItemText(0, _translate("MainWindow", "Camera"))
        self.input_mode.setItemText(1, _translate("MainWindow", "Image"))
        self.input_mode.setItemText(2, _translate("MainWindow", "Video"))
        self.label_import.setText(_translate("MainWindow", "Import"))
        self.occ_class_5.setText(_translate("MainWindow", "0"))
        self.class_5.setText(_translate("MainWindow", "Output Fuse"))
        self.occ_class_3.setText(_translate("MainWindow", "0"))
        self.class_4.setText(_translate("MainWindow", "Radiator Fins"))
        self.class_3.setText(_translate("MainWindow", "Arrester"))
        self.class_2.setText(_translate("MainWindow", "LV Bushing"))
        self.occ_class_1.setText(_translate("MainWindow", "0"))
        self.class_0.setText(_translate("MainWindow", "Transformer Tank"))
        self.occ_class_4.setText(_translate("MainWindow", "0"))
        self.class_1.setText(_translate("MainWindow", "HV Bushing"))
        self.occ_class_0.setText(_translate("MainWindow", "0"))
        self.occ_class_2.setText(_translate("MainWindow", "0"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.actionExit.setText(_translate("MainWindow", "Quit"))
