# Form implementation generated from reading ui file 'ui_tutorial.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TutorialWindow(object):
    def setupUi(self, TutorialWindow):
        TutorialWindow.setObjectName("TutorialWindow")
        TutorialWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TutorialWindow.sizePolicy().hasHeightForWidth())
        TutorialWindow.setSizePolicy(sizePolicy)
        TutorialWindow.setMaximumSize(QtCore.QSize(800, 600))
        TutorialWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(TutorialWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabTutorial = QtWidgets.QTabWidget(self.centralwidget)
        self.tabTutorial.setGeometry(QtCore.QRect(20, 20, 761, 531))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabTutorial.setFont(font)
        self.tabTutorial.setAutoFillBackground(False)
        self.tabTutorial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabTutorial.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabTutorial.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabTutorial.setUsesScrollButtons(True)
        self.tabTutorial.setDocumentMode(False)
        self.tabTutorial.setObjectName("tabTutorial")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textBrowser_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.textBrowser_2.setLineWidth(0)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout.addWidget(self.textBrowser_2)
        self.tabTutorial.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textBrowser_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.textBrowser_3.setLineWidth(0)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.verticalLayout_2.addWidget(self.textBrowser_3)
        self.tabTutorial.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.textBrowser_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.textBrowser_4.setLineWidth(0)
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.verticalLayout_3.addWidget(self.textBrowser_4)
        self.tabTutorial.addTab(self.tab_3, "")
        TutorialWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TutorialWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        TutorialWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TutorialWindow)
        self.statusbar.setObjectName("statusbar")
        TutorialWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TutorialWindow)
        self.tabTutorial.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TutorialWindow)

    def retranslateUi(self, TutorialWindow):
        _translate = QtCore.QCoreApplication.translate
        TutorialWindow.setWindowTitle(_translate("TutorialWindow", "Tutorials"))
        self.textBrowser_2.setHtml(_translate("TutorialWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Follow the steps below:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; font-size:16px; color:#4c4c4c; background-color:#ffffff;\">• </span>Select <span style=\" font-weight:600;\">Camera</span> on the <span style=\" font-weight:600;\">Mode</span> dropdown menu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Select what type of detection needed on <span style=\" font-weight:600;\">Detection Type</span> dropdown menu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Select the desired detection model to use for detection on <span style=\" font-weight:600;\">Detection Model</span> dropdown menu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>When <span style=\" font-weight:600;\">Component </span>is selected the Detection type, a checklist of components is presented. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Checked the desired component to detect.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Detect Button </span>to start the detection process. It automatically opens your camera device and will start recording the session.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Pause Button </span>to temporarily holdup the session.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Resume Button </span>to continue the session.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Stop Button </span>to end the session.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Save Button </span>to keep the recorded session with detected objects bounded by boxes on preferred folder.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Cancel Button </span>to disregard the recorded session.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Notes:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Input Formats: </span>from camera device</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Output Format: </span>.AVI</p></body></html>"))
        self.tabTutorial.setTabText(self.tabTutorial.indexOf(self.tab), _translate("TutorialWindow", "Camera Mode"))
        self.textBrowser_3.setHtml(_translate("TutorialWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Follow the steps below:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; font-size:16px; color:#4c4c4c; background-color:#ffffff;\">• </span>Select<span style=\" font-weight:600;\"> Image</span> on the <span style=\" font-weight:600;\">Mode</span> dropdown menu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Folder Icon</span> to <span style=\" font-weight:600;\">Import </span>an image file.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Select what type of detection needed on <span style=\" font-weight:600;\">Detection Type</span> dropdown menu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Select the desired detection model to use for detection on <span style=\" font-weight:600;\">Detection Model</span> dropdown menu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>When <span style=\" font-weight:600;\">Component </span>is selected the Detection type, a checklist of components is presented. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Checked the desired component to detect.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Detect Button </span>to start the detection process. It automatically show you the output image with detected objects bounded by boxes.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Before Button </span>to view the input image.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">After Button </span>to view the output image</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Save Button </span>to keep the output image on preferred folder.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Cancel Button </span>to disregard the output image.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Notes:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Input Format: </span>.jpg, .jpeg, and .png</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Output Format: </span>.jpg</p></body></html>"))
        self.tabTutorial.setTabText(self.tabTutorial.indexOf(self.tab_2), _translate("TutorialWindow", "Image Mode"))
        self.textBrowser_4.setHtml(_translate("TutorialWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Follow the steps below:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; font-size:16px; color:#4c4c4c; background-color:#ffffff;\">• </span>Select <span style=\" font-weight:600;\">Video</span> on the <span style=\" font-weight:600;\">Mode</span> dropdown menu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Folder Icon</span> to <span style=\" font-weight:600;\">Import </span>a video file.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Select what type of detection needed on <span style=\" font-weight:600;\">Detection Type</span> dropdown menu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Select the desired detection model to use for detection on <span style=\" font-weight:600;\">Detection Model</span> dropdown menu.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>When <span style=\" font-weight:600;\">Component </span>is selected the Detection type, a checklist of components is presented. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">  Checked the desired component to detect.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Detect Button </span>to start the detection process.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Pause Button </span>to temporarily holdup the session.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Resume Button </span>to continue the session.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Stop Button </span>to end the session without processing the whole video.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>The <span style=\" font-weight:600;\">Statust Bar </span>on the lower left corner of the GUI will prompt <span style=\" font-weight:600;\">&quot;Detection Complete&quot;</span> if the whole was done with the detection process.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Save Button </span>to keep the output video with detected objects bounded by boxes on preferred folder.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'HelveticaNeue-Light,-apple-system,AppleSDGothicNeo-Regular,lucida grande,tahoma,verdana,arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji,NotoColorEmoji,EmojiSymbols,Symbola,Noto,Android Emoji,AndroidEmoji,Arial Unicode MS,Zapf Dingbats,AppleColorEmoji,Apple Color Emoji\'; color:#4c4c4c; background-color:#ffffff;\">• </span>Click the <span style=\" font-weight:600;\">Cancel Button </span>to disregard the output video.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Notes:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Input Formats: </span>.mp4 and .AVI</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Output Format: </span>.AVI</p></body></html>"))
        self.tabTutorial.setTabText(self.tabTutorial.indexOf(self.tab_3), _translate("TutorialWindow", "Video Mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TutorialWindow = QtWidgets.QMainWindow()
    ui = Ui_TutorialWindow()
    ui.setupUi(TutorialWindow)
    TutorialWindow.show()
    sys.exit(app.exec())
